import os,sys
FileName=sys.argv[1]
SaveName=sys.argv[2]
print "open:"+str(FileName)
print "saveto:"+str(SaveName)
OpenFilePointer=open(FileName,'rb')  
SaveFilePointer=open(SaveName,'w')
OpenFilePointer.seek(0,0)
PeerIP=""
PeerAS=""
global RestOpenFileLength
RestOpenFileLength=os.path.getsize(FileName)
def Skip(VarLength):
    global RestOpenFileLength
    RestOpenFileLength=RestOpenFileLength-VarLength
    OpenFilePointer.seek(VarLength,1)
def ReadLength(VarLength):
    global RestOpenFileLength
    BaseNum=256**(VarLength-1)
    TempReturnValue=0
    while(VarLength>0):
        TempBinraryValue=OpenFilePointer.read(1)
        RestOpenFileLength=RestOpenFileLength-1
        TempReturnValue=TempReturnValue+int(TempBinraryValue.encode('hex'), 16)*BaseNum
        BaseNum=BaseNum//256
        VarLength=VarLength-1
    return TempReturnValue
while(RestOpenFileLength>0):
    TimeStamp=ReadLength(4)
    Type=ReadLength(2)
    SubType=ReadLength(2)
    MRTLength=ReadLength(4)
    if(Type==13):
        if(SubType==1):
            while(MRTLength>0):
                Skip(4)
                MRTLength=MRTLength-4
                ViewNameLength=ReadLength(2)
                MRTLength=MRTLength-2
                Skip(ViewNameLength)
                MRTLength=MRTLength-ViewNameLength
                PeerCountNum=ReadLength(2)
                MRTLength=MRTLength-2
                while(PeerCountNum>0):
                    PeerCountNum=PeerCountNum-1
                    PeerType=ReadLength(1)
                    MRTLength=MRTLength-1
                    TmpPeerTypeValue=str(bin(PeerType))
                    TmpPeerTypeValue=TmpPeerTypeValue.replace('0b','')
                    TmpPeerValueLength=len(TmpPeerTypeValue)
                    if(TmpPeerTypeValue[TmpPeerValueLength-1]=="0"):
                        IPformat=4
                    if(TmpPeerTypeValue[TmpPeerValueLength-1]=="1"):
                        IPformat=6
                    if((TmpPeerTypeValue[TmpPeerValueLength-2])=="0"):
                        ASformat=2
                    if((TmpPeerTypeValue[TmpPeerValueLength-2])=="1"):
                        ASformat=4
                    Skip(4)
                    MRTLength=MRTLength-4
                    if(IPformat==4):
                        PeerIP=PeerIP+str(ReadLength(1))+"."
                        PeerIP=PeerIP+str(ReadLength(1))+"."
                        PeerIP=PeerIP+str(ReadLength(1))+"."
                        PeerIP=PeerIP+str(ReadLength(1))
                        MRTLength=MRTLength-4
                        PeerIP=PeerIP+" "
                    if(IPformat==6):
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        TempValue=f.read(1)
                        PeerIP=PeerIP+str(TempValue.encode('hex'))
                        MRTLength=MRTLength-16
                        PeerIP=PeerIP+" "
                    PeerAS=PeerAS+str(ReadLength(ASformat))+" "
                    MRTLength=MRTLength-ASformat
                PeerAS=PeerAS.strip(" ")
                PeerIP=PeerIP.strip(" ")
                PeerIP=PeerIP.split(" ")
                PeerAS=PeerAS.split(" ")
        if(SubType==2):
            Skip(4)
            MRTLength=MRTLength-4
            PrefixLength=ReadLength(1)
            MRTLength=MRTLength-1
            Prefix=range(5)
            for i in Prefix:
                Prefix[i]=0
            tmpprefixnum=(PrefixLength+7)/8
            while(tmpprefixnum>0):
                Prefix[4-tmpprefixnum]=ReadLength(1)
                MRTLength=MRTLength-1               
                tmpprefixnum=tmpprefixnum-1
            Prefix=str(Prefix[1])+"."+str(Prefix[2])+"."+str(Prefix[3])+"."+str(Prefix[4])
            EntryCount=ReadLength(2)
            MRTLength=MRTLength-2
            while(EntryCount>0):
                EntryCount=EntryCount-1
                peerindex=ReadLength(2)
                MRTLength=MRTLength-2
                Skip(4)#originated
                MRTLength=MRTLength-4
                BGPAttributeLength=ReadLength(2)
                MRTLength=MRTLength-2
                MRTLength=MRTLength-BGPAttributeLength
                while(BGPAttributeLength>0):
                    Flag=ReadLength(1)
                    BGPAttributeLength=BGPAttributeLength-1
                    Type=ReadLength(1)
                    BGPAttributeLength=BGPAttributeLength-1
                    if(Flag & 16):
                        SingleAttributeLength=ReadLength(2)
                        BGPAttributeLength=BGPAttributeLength-2
                    else:
                        SingleAttributeLength=ReadLength(1)
                        BGPAttributeLength=BGPAttributeLength-1 
                    if(Type==2):
                        ASPath=""
                        while(SingleAttributeLength>0):
                            AssegmentType=ReadLength(1)
                            SingleAttributeLength=SingleAttributeLength-1
                            BGPAttributeLength=BGPAttributeLength-1
                            AssegmentLength=ReadLength(1)
                            SingleAttributeLength=SingleAttributeLength-1
                            BGPAttributeLength=BGPAttributeLength-1
                            if(AssegmentType==2):
                                while(AssegmentLength>0):
                                    if(ASformat==2):
                                        AssegmentValue=ReadLength(2)
                                        SingleAttributeLength=SingleAttributeLength-2
                                        BGPAttributeLength=BGPAttributeLength-2
                                        AssegmentLength=AssegmentLength-1
                                        ASPath=ASPath+str(AssegmentValue)+" "
                                    if(ASformat==4):
                                        AssegmentValue=ReadLength(4)
                                        SingleAttributeLength=SingleAttributeLength-4
                                        BGPAttributeLength=BGPAttributeLength-4
                                        AssegmentLength=AssegmentLength-1
                                        ASPath=ASPath+str(AssegmentValue)+" "    
                            if(AssegmentType==1):
                                while(AssegmentLength>0):
                                    if(ASformat==2):
                                        AssegmentValue=ReadLength(2)
                                        SingleAttributeLength=SingleAttributeLength-2
                                        BGPAttributeLength=BGPAttributeLength-2
                                        AssegmentLength=AssegmentLength-1
                                        ASPath=ASPath+str(AssegmentValue)+"-"
                                    if(ASformat==4):
                                        ssegmentvalue=ReadLength(4)
                                        SingleAttributeLength=SingleAttributeLength-4
                                        BGPAttributeLength=BGPAttributeLength-4
                                        AssegmentLength=AssegmentLength-1
                                        ASPath=ASPath+str(AssegmentValue)+"-"
                        ASPath=ASPath.strip(" ")
                        ASPath=ASPath.strip("-")
                        firstpeeras=ASPath.split(" ")
                        firstpeeras=firstpeeras[0]
                        TmpPosition=0
                        for i in PeerAS:
                            if(i==firstpeeras):
                                break
                            else:
                                TmpPosition=TmpPosition+1
                        TmpIPPos=0
                        for i in PeerIP:
                            if(TmpIPPos==TmpPosition):
                                firstpeerip=i
                                break
                            else:
                                TmpIPPos=TmpIPPos+1
                        SaveFilePointer.write("TABLE_DUMPv2|"+str(TimeStamp)+"|B|"+firstpeerip+"|"+str(firstpeeras)+"|"+Prefix+"/"+str(PrefixLength)+"|"+ASPath+"\n")
                    else:
                        Skip(SingleAttributeLength)
                        BGPAttributeLength=BGPAttributeLength-SingleAttributeLength 
                        SingleAttributeLength=SingleAttributeLength-SingleAttributeLength
    if(Type==12):
        if(SubType==1):
            IPformat=4
        if(SubType==2):
            IPformat=6
        Skip(4)
        MRTLength=MRTLength-4
        if(IPformat==4):
            Prefix=str(ReadLength(1))+"."
            Prefix=Prefix+str(ReadLength(1))+"."
            Prefix=Prefix+str(ReadLength(1))+"."
            Prefix=Prefix+str(ReadLength(1))
            MRTLength=MRTLength-4
        if(IPformat==6):
            TempValue=f.read(1)
            Prefix=str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            Prefix=Prefix+str(TempValue.encode('hex'))
            MRTLength=MRTLength-16
        PrefixLength=ReadLength(1)
        MRTLength=MRTLength-1
        Skip(1)
        MRTLength=MRTLength-1
        Skip(4)#Originated
        MRTLength=MRTLength-4
        if(IPformat==4):
            PeerIP=str(ReadLength(1))+"."
            PeerIP=PeerIP+str(ReadLength(1))+"."
            PeerIP=PeerIP+str(ReadLength(1))+"."
            PeerIP=PeerIP+str(ReadLength(1))
            MRTLength=MRTLength-4
        if(IPformat==6):
            TempValue=f.read(1)
            PeerIP=str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))+":"
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            TempValue=f.read(1)
            PeerIP=PeerIP+str(TempValue.encode('hex'))
            MRTLength=MRTLength-16
        PeerAS=ReadLength(2)
        MRTLength=MRTLength-2
        BGPAttributeLength=ReadLength(2)
        MRTLength=MRTLength-2
        MRTLength=MRTLength-BGPAttributeLength
        if(MRTLength>0):
            print "There my something wrong with MRTLength"
            Pause=sys.stdin.readline()
        while(BGPAttributeLength>0):
            Flag=ReadLength(1)
            BGPAttributeLength=BGPAttributeLength-1
            Type=ReadLength(1)
            BGPAttributeLength=BGPAttributeLength-1
            if(Flag & 16):
                SingleAttributeLength=ReadLength(2)
                BGPAttributeLength=BGPAttributeLength-2
            else:
                SingleAttributeLength=ReadLength(1)
                BGPAttributeLength=BGPAttributeLength-1 
            if(Type==2):
                ASPath=""
                while(SingleAttributeLength>0):
                    AssegmentType=ReadLength(1)
                    print "AssegmentType="+str(AssegmentType)
                    SingleAttributeLength=SingleAttributeLength-1
                    BGPAttributeLength=BGPAttributeLength-1
                    AssegmentLength=ReadLength(1)
                    print "AssegmentLength="+str(AssegmentLength)
                    SingleAttributeLength=SingleAttributeLength-1
                    BGPAttributeLength=BGPAttributeLength-1
                    if(AssegmentType==2):
                        while(AssegmentLength>0):
                            AssegmentValue=ReadLength(2)
                            SingleAttributeLength=SingleAttributeLength-2
                            BGPAttributeLength=BGPAttributeLength-2
                            AssegmentLength=AssegmentLength-1
                            ASPath=ASPath+str(AssegmentValue)+" "
                    if(AssegmentType==1):
                        while(AssegmentLength>0):
                            AssegmentValue=ReadLength(2)
                            SingleAttributeLength=SingleAttributeLength-2
                            BGPAttributeLength=BGPAttributeLength-2
                            AssegmentLength=AssegmentLength-1
                            ASPath=ASPath+str(AssegmentValue)+"-"
                ASPath=ASPath.strip(" ")
                ASPath=ASPath.strip("-")
                SaveFilePointer.write("TABLE_DUMP|"+str(TimeStamp)+"|B|"+PeerIP+"|"+str(PeerAS)+"|"+Prefix+"/"+str(PrefixLength)+"|"+ASPath+"\n")
            else:
                Skip(SingleAttributeLength)
                BGPAttributeLength=BGPAttributeLength-SingleAttributeLength
                SingleAttributeLength=SingleAttributeLength-SingleAttributeLength

OpenFilePointer.close()  
SaveFilePointer.close()
